
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firstshopdb
    username: admin
    password: 973341
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
application:
  security:
    jwt:
      access-key:
        value: "gpgdKY9zR4hebFb2wT67AlgsKmbTOmKoyqmGym1dKmM="
        expiration-time: 5
      refresh-key:
        value: "7+bbUaAIaRFDce4rxQLu5QFPqooqHLgfN5mnDB7PNT4="
        expiration-time:  10

